### ISSUE TITLE
按照教程安装报错

### ISSUE THREAD

**Issue by YoungShy** [pengcong90/elasticsearch-analysis-hanlp#12]
[2018-08-29T14:19:56,487][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[vFHEl-z][generic][T#3]], exiting
java.lang.ExceptionInInitializerError: null
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:363) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:177) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:155) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:162) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:367) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:453) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:497) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.gateway.Gateway.performStateRecovery(Gateway.java:127) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.gateway.GatewayService$1.doRun(GatewayService.java:223) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:725) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.3.2.jar:6.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_131]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_131]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_131]
	at java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1262) ~[?:1.8.0_131]
	at java.lang.System.getProperties(System.java:630) ~[?:1.8.0_131]
	at org.elasticsearch.index.analysis.HanLPTokenizerFactory.<clinit>(HanLPTokenizerFactory.java:22) ~[?:?]
	... 14 more

**Comment by pengcong90** [comment]
https://github.com/pengcong90/elasticsearch-analysis-hanlp/issues/4

**Comment by pengcong90** [comment]
2、修改es config目录下的jvm.options文件，最后一行添加

-Djava.security.policy=../plugins/analysis-hanlp/plugin-security.policy

**Comment by DengGuangXue** [comment]
> 2、修改es config目录下的jvm.options文件，最后一行添加
> 
> -Djava.security.policy=../plugins/analysis-hanlp/plugin-security.policy

我按上面步骤做了，还是报错，如下所示：
[2019-04-20T12:03:03,834][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [k1WDWmL] fatal error in thread [elasticsearch[k1WDWmL][analyze][T#1]], exiting
java.lang.ExceptionInInitializerError: null
        at com.hankcs.hanlp.seg.Segment.seg(Segment.java:338) ~[?:?]
        at com.hankcs.lucene4.HanlpSegmenter.next(HanlpSegmenter.java:65) ~[?:?]
        at com.hankcs.lucene4.HanLPTokenizer.incrementToken(HanLPTokenizer.java:46) ~[?:?]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:275) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:252) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:170) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:115) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.6.2.jar:6.6.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_65]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_65]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_65]
        at java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1262) ~[?:1.8.0_65]
        at java.lang.System.getProperties(System.java:630) ~[?:1.8.0_65]
        at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:240) ~[?:?]
        ... 13 more
求指教，谢谢！

**Comment by DengGuangXue** [comment]
![image](https://user-images.githubusercontent.com/35302899/56452605-0b10ae00-6365-11e9-839f-a88490fc5529.png)

**Comment by DengGuangXue** [comment]
> 2、修改es config目录下的jvm.options文件，最后一行添加
> 
> -Djava.security.policy=../plugins/analysis-hanlp/plugin-security.policy

我去掉 ../ 后，发现就可以了
-Djava.security.policy=plugins/analysis-hanlp/plugin-security.policy
