### ISSUE TITLE
ES6.5.3按照教程，Windows 7安装报错!

### ISSUE THREAD

**Issue by NikolaDai** [pengcong90/elasticsearch-analysis-hanlp#17]
[2018-12-25T09:34:00,228][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [k
1dzoLq] fatal error in thread [elasticsearch[k1dzoLq][analyze][T#1]], exiting
java.lang.ExceptionInInitializerError: null
        at com.hankcs.hanlp.seg.Segment.seg(Segment.java:338) ~[?:?]
        at com.hankcs.lucene4.HanlpSegmenter.next(HanlpSegmenter.java:65) ~[?:?]

        at com.hankcs.lucene4.HanLPTokenizer.incrementToken(HanLPTokenizer.java:
46) ~[?:?]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction
.simpleAnalyze(TransportAnalyzeAction.java:267) ~[elasticsearch-6.5.3.jar:6.5.3]

        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction
.analyze(TransportAnalyzeAction.java:244) ~[elasticsearch-6.5.3.jar:6.5.3]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction
.shardOperation(TransportAnalyzeAction.java:165) ~[elasticsearch-6.5.3.jar:6.5.3
]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction
.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.5.3.jar:6.5.3]

        at org.elasticsearch.action.support.single.shard.TransportSingleShardAct
ion$1.doRun(TransportSingleShardAction.java:112) ~[elasticsearch-6.5.3.jar:6.5.3
]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreserv
ingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.5.3.jar:6.5.
3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37) ~[elasticsearch-6.5.3.jar:6.5.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149) ~[?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624) ~[?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.security.AccessControlException: access denied ("java.util.Prope
rtyPermission" "*" "read,write")
        at java.security.AccessControlContext.checkPermission(AccessControlConte
xt.java:472) ~[?:1.8.0_171]
        at java.security.AccessController.checkPermission(AccessController.java:
884) ~[?:1.8.0_171]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~
[?:1.8.0_171]
        at java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:
1262) ~[?:1.8.0_171]
        at java.lang.System.getProperties(System.java:630) ~[?:1.8.0_171]
        at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:240) ~[?:?]
        ... 13 more

**Comment by NikolaDai** [comment]
已经解决，主要是需要将jvm.options中添加一行改为windows下识别的绝对地址，比如我本地是：
-Djava.security.policy=C:\elasticsearch\6.5.3\plugins\analysis-hanlp\plugin-security.policy

**Comment by alittlebitcool** [comment]
linux添加了就有权限错误，不添加就用不了怎么办啊
