### ISSUE TITLE
ES 7.7.0是否支持？

### ISSUE THREAD

**Issue by legenstrike** [pengcong90/elasticsearch-analysis-hanlp#31]
目前按照说明已经完成插件的安装但是发生个错误导致无法启动，请帮忙查看原因？
[2020-06-03T17:05:23,142][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-local] fatal error in thread [main], exiting
java.lang.NoSuchMethodError: org.elasticsearch.rest.BaseRestHandler.<init>(Lorg/elasticsearch/common/settings/Settings;)V
	at com.hankcs.rest.RestDicOperateAction.<init>(RestDicOperateAction.java:36) ~[?:?]
	at org.elasticsearch.plugin.analysis.hanlp.AnalysisHanlpPlugin.getRestHandlers(AnalysisHanlpPlugin.java:71) ~[?:?]
	at org.elasticsearch.action.ActionModule.initRestHandlers(ActionModule.java:781) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.node.Node.<init>(Node.java:633) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.node.Node.<init>(Node.java:264) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.7.0.jar:7.7.0]

**Comment by jtajiana** [comment]
请问这个问题解决了吗？是不是jar冲突了？
