### ISSUE TITLE
镜像elasticsearch7.14.0版本、v7.0.1， v6.8.3，按照流程走的，都是出现如下问题，求教

### ISSUE THREAD

**Issue by xiangchao886** [pengcong90/elasticsearch-analysis-hanlp#36]
java.lang.IllegalArgumentException: plugin policy [/usr/share/elasticsearch/plugins/analysis-hanlp/plugin-security.policy] contains illegal permission ("java.io.FilePermission" "-#plus" "read,write") in global grant
 	at org.elasticsearch.bootstrap.PolicyUtil.validatePolicyPermissionsForJar(PolicyUtil.java:303)
 	at org.elasticsearch.bootstrap.PolicyUtil.validatePolicyPermissions(PolicyUtil.java:313)
 	at org.elasticsearch.bootstrap.PolicyUtil.getPluginPolicyInfo(PolicyUtil.java:324)
 	at org.elasticsearch.bootstrap.Security.getPluginAndModulePermissions(Security.java:142)
 	at org.elasticsearch.bootstrap.Security.configure(Security.java:106)
 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214)
 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:399)
 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
 	at org.elasticsearch.cli.Command.main(Command.java:79)
 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log

**Comment by xiangchao886** [comment]
close

**Comment by 2822132073** [comment]
麻烦问一下，你这个后面自动加的#plus怎么解决的

**Comment by xiangchao886** [comment]
修改为合法的文件路径模式:

**Comment by xiangchao886** [comment]
好久的问题了，修改为合法的文件路径模式： "/path/to/hanlp/data/-" 这种的试试
