### ISSUE TITLE
请问plugin-security.policy应该怎么设置？

### ISSUE THREAD

**Issue by gonggawang** [pengcong90/elasticsearch-analysis-hanlp#4]
我的plugin-security.policy文件内容是：
grant {
    permission java.util.PropertyPermission "*", "read,write";
};
也修改了es config目录下的jvm.options文件
es启动时已经加载 -Djava.security.policy=../plugins/analysis-hanlp/plugin-security.policy

但用hanlp分词时es后台报错：
java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_66]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_66]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_66]
        at java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1262) ~[?:1.8.0_66]
        at java.lang.System.getProperties(System.java:630) ~[?:1.8.0_66]
        at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:240) ~[?:?]

这个问题折磨了我好长时间，查了很多资料，也没找到原因，特意登录来问问。如能指点，不胜感激。

**Comment by pengcong90** [comment]
系统环境是什么

**Comment by gonggawang** [comment]
win10

**Comment by pengcong90** [comment]
是用服务启动的吗？

**Comment by pengcong90** [comment]
服务启动的话建议修改Java\jdk1.8.0_112\jre\lib\security中的java.policy文件添加上面的权限控制，windows下面这个不起作用，不知道为什么

**Comment by gonggawang** [comment]
不是服务启动，是bat启动的。好的，我试试。多谢！

**Comment by gonggawang** [comment]
在[JDK]\jre\lib\security中的java.policy文件添加上面的权限控制后，win
10下可以用hanlp分词了，谢谢！

**Comment by gonggawang** [comment]
不过出现另外的问题：找不到hanlp.properties
Linux下也出现这个问题
Predefine.HANLP_PROPERTIES_PATH:/mnt/d/linux/elasticsearch-5.6.3/plugins/analysis-hanlp/hanlp.properties
Oct 31, 2017 7:27:56 AM com.hankcs.hanlp.HanLP$Config <clinit>
SEVERE: 没有找到hanlp.properties，可能会导致找不到data
========Tips========
请将hanlp.properties放在下列目录：
Web项目则请放到下列目录：
Webapp/WEB-INF/lib
Webapp/WEB-INF/classes
Appserver/lib
JRE/lib
并且编辑root=PARENT/path/to/your/data
现在HanLP将尝试从/mnt/d/linux/elasticsearch-5.6.3/bin读取data……

**Comment by pengcong90** [comment]
你的hanlp.properties这个文件是在/mnt/d/linux/elasticsearch-5.6.3/plugins/analysis-hanlp/hanlp.properties这个目录下吗？或者你加下我qq 625194329，我帮你处理一下

**Comment by gonggawang** [comment]
配置文件位置没错，稍等我加你QQ

**Comment by kkkktigb** [comment]
-Djava.security.policy=../plugins/analysis-hanlp/plugin-security.policy 我也跟你一样的问题，这个路径错了

**Comment by guoyanbiao520** [comment]
您好，我想问下现在hanlp1.63版本支持动态词典，这个在这个插件里能做么

**Comment by stevenQinwen** [comment]
这个到底是什么问题啊

**Comment by hdulbj** [comment]
我也碰到了一模一样的问题，还未解决

**Comment by 1120025919** [comment]
java 安全策略问题
修改\jdk\jdk-8u121\jre\lib\security\java.policy
permission java.net.SocketPermission "*", "connect,resolve";
permission java.io.FilePermission "*","read";

**Comment by tangwang** [comment]
错误也是access denied ("java.io.FilePermission" "/usr/share/elasticsearch/data/model/perceptron/large/cws.bin" "read")
1. 在插件目录下的plugin-security.policy、以及jdk目录下的conf/security/java.policy下添加：
    permission java.io.FilePermission "<<ALL FILES>>", "read,write,delete";
或者
    permission java.net.SocketPermission "*", "connect,resolve";
    permission java.io.FilePermission "*","read";
都没用。
2. data目录不应该在 plugins/analysis-hanlp下面吗？为什么跑到与plugins同级了？

系统环境：ES版本和插件版本都是7.10.2，jdk1.8, centos，plugins/analysis-hanlp下面有data目录、外面也有data、属主用户都是elasticsearch用户、权限777，确保了路径存在并且权限没问题

 卡在这里挺久了（甚至尝试过更换jdk版本，也没用），求教
